version: '2'

services:
  frontend:
    image: eeacms/clms-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      API_PATH: 'http://localhost:8080/Plone'

  backend:
    image: eeacms/clms-backend:latest
    ports:
      - 8080:8080
    environment:
      CORS_ALLOW_ORIGIN: '*'
    depends_on:
      - memcached
    volumes:
      - data:/data

  memcached:
    image: memcached
    command:
      - '-m'
      - '512'

volumes:
  data:
    driver: local
